from routers.admin import router as admin_router
from routers.alumni import router as alumni_router
from routers.careers import router as careers_router
from routers.coach import router as coach_router
from routers.health import router as health_router
from routers.job_readiness import router as job_readiness_router
from routers.journey import router as journey_router
from routers.learning import router as learning_router
from routers.onboarding import router as onboarding_router
from routers.opportunities import router as opportunities_router
from routers.sports import router as sports_router
from routers.universities import router as universities_router
